project:
  type: website
  output-dir: docs

website:
  title: SI07-001-G Information systems management
  # site-url: https://guillaumegilles.github.io/
  # description: A website at the crossroad of technology, social science, society, economy, and history.
  # image: 

  # Github action buttons
  # repo-url: https://github.com/guillaumegilles/guillaumegilles.github.io/
  # repo-actions: [issue]

  # Social Metadata
  # favicon: images/cat.png
  # twitter-card: true
  # open-graph: true

  # Google Analytics
  # If you are forking my repo to develop content or your own purposes
  # please disable my Google Analytics tag during development. If building
  # your own site, replace our GA tag with your own GA tag before 
  # deployment. This will prevent your activity being tracked and counted
  # in our analytics dashboard. Thank you!
  google-analytics: G-6BXJC408ED

  # Website navigation
  page-navigation: true
  back-to-top-navigation: true

  # Navbar
  navbar:
    logo: ../../images/cat.png
    title: false
    right:
      - text: ABOUT
        href: ../../about.html
      - text: PROJECTS
        href: ../../projects.html
      - text: TEACHING
        href: ../../teaching.html
      - text: BLOG
        href: ../../blog.html

  sidebar:
    search: true
    tools:
      - icon: github
        text: GitHub
        href: https://github.com/guillaumegilles/management-information-system
      - icon: code-square
        text: Moodle
        href: https://moodle.essca.fr/course/view.php?id=12518
    contents:
      - text: HOME
        href: index.qmd
      - section: INFORMATION
        contents:
          - href: planning.qmd
          - href: syllabus.qmd
      - section: "Module 1: Foundations of Information Systems Management"
        contents:
          - href: session-1.qmd
          - href: session-2.qmd
      - section: "Module 2: IS Strategy & Decision-Making"
        contents:
          - href: session-3.qmd
          - href: session-4.qmd
      - section: "Module 3: Ethics, CSR, and IS Management"
        contents:
          - href: session-5.qmd
          - href: session-6.qmd
      - section: "Module 4: Information Systems Implementation & Change Management"
        contents:
          - href: session-7.qmd
          - href: session-8.qmd
      - section: "Module 5: Emerging Trends & Innovations in IS"
        contents:
          - href: session-9.qmd
          - href: session-10.qmd
      - section: "Module 6: Practical Applications & Case Studies"
        contents:
          - href: session-11.qmd
          - href: session-12.qmd
      - section: "Module 7: Final Projects & Review"
        contents:
          - href: session-13.qmd
          - href: session-14.qmd
          - href: session-15.qmd
  
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/guillaumegilles/
      - icon: file-earmark-code-fill
        href: https://www.kaggle.com/guillaumegilles
      - icon: github
        href: https://github.com/guillaumegilles

format:
  html:
    page-layout: full
    theme: flaty

    # References
    citation-location: margin

    email-obfuscation: javascript
